# Generated by Django 2.2.3 on 2023-08-14 14:56

from django.db import migrations, models
import imageai.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identify_object', models.CharField(max_length=255)),
                ('inputted_image', models.ImageField(upload_to=imageai.models.upload_to)),
                ('outputted_image', models.ImageField(blank=True, null=True, upload_to=imageai.models.upload_to)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
